name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - xgboost
  - lightgbm
  - catboost
  - scikit-learn
  - scikit-garden
  - glob2
  - pip
  - joblib
  - numba
  - numexpr
  
  
